export const FETCH_ALL_DATA_REQ = "FETCH_ALL_DATA_REQ";
export const FETCH_ALL_DATA_SUCCESS = "FETCH_ALL_DATA_SUCCESS";
export const FETCH_ALL_DATA_FAILURE = "FETCH_ALL_DATA_FAILURE";

export const ADD_TO_CART_ITEM_REQ = "ADD_TO_CART_ITEM_REQ";
export const ADD_TO_CART_ITEM_SUCCESS = "ADD_TO_CART_ITEM_SUCCESS";
export const ADD_TO_CART_ITEM_FAILURE = "ADD_TO_CART_ITEM_FAILURE";

export const INC_CART_ITEM_QUANTITY = "INC_CART_ITEM_QUANTITY";
